### ISSUE TITLE
mixed active content error on demo page

### ISSUE THREAD

**Issue by Cyrille37** [makinacorpus/osm-transport-editor#5]
Hi,

on demo page https://makinacorpus.github.io/osm-transport-editor there is the Firefox error: "Blocage du chargement du contenu mixte actif (mixed active content) « http://overpass-api.de/api/interpreter »"

Perhaps because the demo page is HTTPS but overpass call is HTTP.

Cheers.

**Comment by frodrigo** [comment]
This tools is unmaintained. It requires broken dependencies. Even with HTTPS it will not work.
